version: "3.7"
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/var/www
    tty: true
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2-alpine
    volumes:
      - ./var/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: linktree
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: linktree
    ports:
      - "54321:5432"

  mailer:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025


